creation_rules:
  - path_regex: '\.env$'
    age: >-
      age1zptpgxhs9chnkudu69qut2hn706pmyngasvaz4ppf452un2x7p2ss6j96f,
      age15ju3v4rrktqp7nf0ucxswlm7zafeh4t7g535l3w4ck8s632gqgvqsv4svn

# 1. Ayushman
# 2. Vivek